git:
  depth: false
addons:
  sonarcloud:
    organization: "lucacappelletti94-github"
    token:
      secure: "kcYLIl88ihtlgq+El/7x+Kr1fLUEfHNLcw8phg11bxvVvFFvaZ8k3zdocTbaJlL053sLnuJpk3GCBpdZvvEkRabbchryhf4N1igEAqvqYPXLidtJ1fdmOZv+CdVEiT3quQk3gNKq3DjBt2ofweGbsj2jDF2QGBRdek2GvPsvet+dWRBKoJbpDQLXFC64es+aQNdZKZotm/5keBAkY/BetOyZmDIVz3bfZMIlO13e03V5pRx7gohPgZJoRM0HQxyYLKDe2oST1l4OnXtT7mKaLzc6GSHUCWTl8J70IlvGmn3GIYEmz+AdzqchSD2EmEzr4V0sUp30j6JYQjcTR47kE4wTZlslGgwJbsJbhKsPCPxymyYFsy/Y6b/rhRqWu79V2yqgeeL048boF3saTmiTsidmZUyfE0+7nOQg/Xc1+utUe5pECOOEpDL+KxI6YqXspN3vZu1UD6Qf4LXpec+BmULfCIAFpz9zf/YWVFW8e020iYtLpxpGTtmvNlnQFllVIdBBaKsdIQHCHunP65D/NnfDGoO8jWNy5lL7Wwa+eCSJ7R39jWyZLio66AtAb20bT60f2HtS/5y8H1YWD1CDTfgI+jXqQivf4Q8VYlFoAOCkYdRzzi2yrdTDwnBcEYdTGxHlQgkjCg8vvsYuARvNW7nmzDj8ABmfeT5Y5Cz7/fE="
language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=downloaders --cov-report xml:coverage.xml 
- coverage combine --append || true
- coverage report
- coverage xml
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
